export default function Subjects() {
    let subjects = [
        { id: 1, value:'English' },
        { id: 2, value:'Mathematics'},
        { id: 3, value:'Physical Sciences' },
        { id: 4, value:'Life Sciences' },
        { id: 5, value:'Physical Sciences'},
        { id: 5, value: "Geography" },
        { id: 6, value: "History" },
        { id: 7, value: "Natural Sciences" },
        { id: 8, value: "Social Sciences" },
        { id: 9, value: "Life Orientation" },
        { id: 10, value: "Technology" },
        { id: 11, value: "Arts and Culture" },
        { id: 12, value: "Economic and Management Sciences (EMS)" },
        { id: 13, value: "Physical Education" },
        { id: 14, value: "Accounting" },
        { id: 15, value: "Business Studies" },
        { id: 16, value: "Economics" },
        { id: 17, value: "Information Technology (IT)" },
        { id: 18, value: "Visual Arts" },
        { id: 19, value: "Music" },
        { id: 20, value: "Drama" },
        { id: 21, value: "Life Orientation" },
        { id: 22, value: "Technology" },
        { id: 23, value: "Business Administration" },
        { id: 24, value: "Computer Science" },
        { id: 25, value: "Engineering" },
        { id: 26, value: "Law" },
        { id: 27, value: "Health Sciences" },
        { id: 28, value: "Education" },
        { id: 29, value: "Marketing" },
        { id: 30, value: "Finance" },
        { id: 31, value: "Psychology" },
        { id: 32, value: "Sociology" },
        { id: 33, value: "Political Science" },
        { id: 34, value: "Journalism and Media Studies" },
        { id: 35, value: "Fine Arts" },
        { id: 36, value: "Other" }
    ]
    return subjects;
}